#ifndef DEPARTMENT_H
#define DEPARTMENT_H

enum class Department{
    DEVELOPMENT,
    TESTING,
    INTEGRATION
};
//INSTEAD OF DAYS 
//Y USING ENUM BEACUSE CATEGORICAL DATA LIKE GENDER, COLOR 
//WHERE OPTIONS ARE LIMITED  
#endif // DEPARTMENT_H
